### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by danielcasto** [Data-for-Good-by-UF/AIR#5]
Validate all info entered in the text boxes. The one I am most concerned about is the start and end dates, they have to be of the correct date format (specified in program) and have to be future dates.

**Comment by colinnaehr** [comment]
Sample app needs to check for the string to be 1 of 4 types of pollutants, 2 must be 1 of 50 states, and dates must be in valid format as well as in the future. In case of failure in any of these categories, an error will appear

**Comment by danielcasto** [comment]
Dates are now validated when entered. We will want to test it to make sure it fully works. Additionally, it may be good to add a text box to tell user what specifically about their input is invalid.

**Comment by danielcasto** [comment]
All inputs were validated as specified in previous comment by Colin. There is a label on the window that displays error message in cases of bad inputs.
